{
  description = "Zallet — reproducible static-musl builds (amd64 + arm64)";
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    crane.url = "github:ipetkov/crane/v0.20.3";
    rust-overlay = { url = "github:oxalica/rust-overlay"; inputs.nixpkgs.follows = "nixpkgs"; };
    flake-utils.url = "github:numtide/flake-utils";
  };
  outputs = { self, nixpkgs, crane, rust-overlay, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; overlays = [ (import rust-overlay) ]; };
        muslTarget =
          if system == "aarch64-linux" then "aarch64-unknown-linux-musl"
          else "x86_64-unknown-linux-musl";
        # cargo reads the per-target env var named after the UPPERCASED triple
        # with -/. → _ (e.g. CC_x86_64_unknown_linux_musl). Derive it from the
        # active target so BOTH arches get the musl-clang toolchain — hardcoding
        # the aarch64 name left x86_64-on-x86 builds without a CC for the *-sys
        # crates.
        targetEnvSuffix =
          builtins.replaceStrings [ "-" "." ] [ "_" "_" ] muslTarget;
        rustToolchain = pkgs.rust-bin.stable."1.88.0".default.override {
          targets = [ muslTarget ];
        };
        craneLib = (crane.mkLib pkgs).overrideToolchain rustToolchain;
        ftlOrCargo = path: type:
          (builtins.match ".*\\.ftl$" path != null)
          || (builtins.match ".*/i18n\\.toml$" path != null)
          || (craneLib.filterCargoSources path type);
        src = pkgs.lib.cleanSourceWith { src = ./.; filter = ftlOrCargo; name = "source"; };
        # The *-sys C/C++ deps need a coherent musl toolchain. pkgsMusl.clangStdenv.cc
        # is a clang targeting aarch64-musl with libc++ — this resolves a two-sided
        # conflict that ad-hoc cc choices can't:
        #   * pqcrypto/pqclean (C): its compat.h does `#include <features.h>` only
        #     when `!defined(__clang__)`; clang defines __clang__ so it skips that
        #     glibc-only header (gcc would pull it and fail to compile under musl).
        #   * zcash_script (C++): clangStdenv links LLVM libc++ built against musl,
        #     instead of gcc's libstdc++ which references glibc-only symbols
        #     (__libc_single_threaded, __cxa_thread_atexit_impl) that break the
        #     static-musl link.
        # This mirrors how StageX's pre-integrated clang+libc++ pallet works on amd64.
        clangCC = pkgs.pkgsMusl.clangStdenv.cc;
        # Build one of the binaries Zallet ships. Since zcash/zallet#540 each
        # chain backend lives in its own cargo workspace with its own lockfile
        # (backends/zebra → zallet-zebra, backends/zaino → zallet-zaino),
        # and the user-facing `zallet` binary is a thin launcher in the root
        # workspace that dispatches to whichever backend binary the config
        # names. `manifestDir` selects the workspace; the generated share tree
        # (completions/manpages) is emitted by zallet-core's build script and
        # collected once, from the zebra-state backend build.
        #
        # NOTE: the nix outputs do NOT include debian-copyright — it is the
        # union of all three graphs and is generated by `gen-copyright` on the
        # StageX (amd64) path; the license inventory is arch-independent, so
        # the release workflow reuses the amd64 copy for the arm64 deb.
        mkZallet = { manifestDir ? null, binName, features ? [ ], collectShare ? false }:
          craneLib.buildPackage ({
          inherit src;
          pname = binName;
          version = (craneLib.crateNameFromCargoToml {
            cargoToml =
              if manifestDir == null then ./zallet/Cargo.toml
              else ./. + "/${manifestDir}/Cargo.toml";
          }).version;
          strictDeps = true;
          cargoLock =
            if manifestDir == null then ./Cargo.lock
            else ./. + "/${manifestDir}/Cargo.lock";
          cargoExtraArgs = "--locked --bin ${binName}"
            + pkgs.lib.optionalString (manifestDir != null)
                " --manifest-path ${manifestDir}/Cargo.toml"
            + pkgs.lib.optionalString (features != [ ])
                " --features ${pkgs.lib.concatStringsSep "," features}";
          CARGO_BUILD_TARGET = muslTarget;
          # Static musl; use the musl clang as the linker so libc++ + crt resolve
          # coherently (a generic cc-wrapper mis-targets gnu vs musl here).
          CARGO_BUILD_RUSTFLAGS = "-C target-feature=+crt-static -C codegen-units=1 -C linker=${clangCC}/bin/cc -C link-arg=-static";
          nativeBuildInputs = with pkgs; [ protobuf llvmPackages.clang pkg-config git ];
          LIBCLANG_PATH = "${pkgs.llvmPackages.libclang.lib}/lib";
          PROTOC = "${pkgs.protobuf}/bin/protoc";
          doCheck = false;
          # zallet/build.rs (clap_complete + clap_mangen) emits completions,
          # manpages and debian-copyright into target/<triple>/release/{completions,
          # manpages} + debian-copyright. crane installs only the binary, so copy
          # those generated assets into $out/share/zallet — the deb matrix +
          # the StageX export layout expect them there. Only the default
          # (zebra-state) binary carries the share tree + keeps the `zallet` name.
          postInstall = pkgs.lib.optionalString collectShare ''
            # build.rs writes completions/ + manpages/ into the cargo target dir
            # (derived from OUT_DIR's 4th ancestor → <target>/<triple>/release).
            # crane's CARGO_TARGET_DIR isn't necessarily ./target, so SEARCH for
            # the generated dirs rather than assuming a fixed path — a fixed
            # `target/<triple>/release` silently missed them under crane, which
            # left the .deb step globbing for completions/zallet.bash and failing.
            mkdir -p "$out/share/zallet"
            comp="$(find . -type d -name completions -path '*release*' 2>/dev/null | head -1)"
            mans="$(find . -type d -name manpages    -path '*release*' 2>/dev/null | head -1)"
            if [ -n "$comp" ]; then cp -r "$comp" "$out/share/zallet/completions"; else
              echo "postInstall: completions/ not found under target tree" >&2; exit 1; fi
            if [ -n "$mans" ]; then cp -r "$mans" "$out/share/zallet/manpages"; fi
          '';
        }
        # Per-target CC/CXX for the *-sys crates' cc-rs, keyed by the active
        # triple (CC_x86_64_unknown_linux_musl on amd64, CC_aarch64_... on arm64).
        // {
          "CC_${targetEnvSuffix}" = "${clangCC}/bin/cc";
          "CXX_${targetEnvSuffix}" = "${clangCC}/bin/c++";
        });
        # The zebra-state backend binary owns the completions/manpages share
        # tree that the deb + StageX export consume (both backends generate
        # identical trees; one copy suffices).
        zallet-zebra = mkZallet {
          manifestDir = "backends/zebra";
          binName = "zallet-zebra";
          features = [ "rpc-cli" "zcashd-import" ];
          collectShare = true;
        };
        zallet-zaino = mkZallet {
          manifestDir = "backends/zaino";
          binName = "zallet-zaino";
          features = [ "rpc-cli" "zcashd-import" ];
        };
        # The user-facing launcher (root workspace): dispatches to the backend
        # binary named by the config's `backend` key, installed next to itself.
        zallet-launcher = mkZallet { binName = "zallet"; };
        # Everything the runtime image layout carries, merged: the launcher and
        # both backends side by side, plus the share tree.
        zallet = pkgs.symlinkJoin {
          name = "zallet";
          paths = [ zallet-launcher zallet-zebra zallet-zaino ];
        };
      in {
        packages.default = zallet;
        packages.zallet = zallet;
        packages.zallet-launcher = zallet-launcher;
        packages.zallet-zebra = zallet-zebra;
        packages.zallet-zaino = zallet-zaino;
      });
}
