use std::path::PathBuf;

use clap::{Parser, builder::Styles};

#[cfg(zallet_build = "wallet")]
use clap::ArgGroup;

#[cfg(zallet_build = "wallet")]
use uuid::Uuid;

#[cfg(outside_buildscript)]
use abscissa_core::{Command, Runnable};

use crate::fl;

#[derive(Debug, Parser)]
#[cfg_attr(outside_buildscript, derive(Command))]
#[command(name = "zallet", author, about, version)]
#[command(help_template = format!("\
{{before-help}}{{about-with-newline}}
{}{}:{} {{usage}}

{{all-args}}{{after-help}}\
    ",
    Styles::default().get_usage().render(),
    fl!("usage-header"),
    Styles::default().get_usage().render_reset()))]
#[command(next_help_heading = fl!("flags-header"))]
pub struct EntryPoint {
    #[command(subcommand)]
    pub(crate) cmd: ZalletCmd,

    /// Enable verbose logging
    #[arg(short, long)]
    pub(crate) verbose: bool,

    /// Specify the data directory for the Zallet wallet.
    ///
    /// This must be an absolute path.
    ///
    /// [default: $HOME/.zallet]
    #[arg(short, long)]
    pub(crate) datadir: Option<PathBuf>,

    /// Use the specified configuration file.
    ///
    /// Relative paths will be prefixed by the datadir.
    #[arg(short, long)]
    pub(crate) config: Option<PathBuf>,
}

#[derive(Debug, Parser)]
#[cfg_attr(outside_buildscript, derive(Command, Runnable))]
pub(crate) enum ZalletCmd {
    /// The `start` subcommand
    Start(StartCmd),

    /// Generate an example `zallet.toml` config.
    ExampleConfig(ExampleConfigCmd),

    /// Generate a `zallet.toml` config from an existing `zcash.conf` file.
    #[cfg(all(zallet_build = "wallet", feature = "zcashd-import"))]
    MigrateZcashConf(MigrateZcashConfCmd),

    /// Add the keys and transactions of a zcashd wallet.dat file to the wallet database.
    #[cfg(all(zallet_build = "wallet", feature = "zcashd-import"))]
    MigrateZcashdWallet(MigrateZcashdWalletCmd),

    /// Generate the wallet's age encryption identity.
    #[cfg(zallet_build = "wallet")]
    GenerateEncryptionIdentity(GenerateEncryptionIdentityCmd),

    /// Initialize wallet encryption.
    #[cfg(zallet_build = "wallet")]
    InitWalletEncryption(InitWalletEncryptionCmd),

    /// Generate a BIP 39 mnemonic phrase and store it in the wallet.
    #[cfg(zallet_build = "wallet")]
    GenerateMnemonic(GenerateMnemonicCmd),

    /// Import a BIP 39 mnemonic phrase into the wallet.
    #[cfg(zallet_build = "wallet")]
    ImportMnemonic(ImportMnemonicCmd),

    /// Export an encrypted BIP 39 mnemonic phrase from the wallet.
    #[cfg(zallet_build = "wallet")]
    ExportMnemonic(ExportMnemonicCmd),

    /// Confirm that a BIP 39 mnemonic phrase generated by the wallet has been backed up.
    #[cfg(zallet_build = "wallet")]
    ConfirmBackup(ConfirmBackupCmd),

    /// Import a transparent address into the wallet as watch-only.
    #[cfg(all(zallet_build = "wallet", feature = "transparent-key-import"))]
    ImportAddress(ImportAddressCmd),

    /// Adds a user authorization for the JSON-RPC interface.
    AddRpcUser(AddRpcUserCmd),

    /// Communicate with a Zallet wallet's JSON-RPC interface.
    #[cfg(feature = "rpc-cli")]
    Rpc(RpcCliCmd),

    /// Commands for repairing broken wallet states.
    #[command(subcommand)]
    Repair(RepairCmd),

    /// Hidden regtest-only commands.
    #[command(subcommand, hide = true)]
    Regtest(RegtestCmd),
}

/// `start` subcommand
#[derive(Debug, Parser)]
#[cfg_attr(outside_buildscript, derive(Command))]
pub(crate) struct StartCmd {}

/// `example-config` subcommand
#[derive(Debug, Parser)]
#[cfg_attr(outside_buildscript, derive(Command))]
pub(crate) struct ExampleConfigCmd {
    /// Where to write the Zallet config file.
    ///
    /// - By default, the default Zallet config file path is used.
    /// - The value `-` will write the config to stdout.
    #[arg(short, long)]
    pub(crate) output: Option<String>,

    /// Force an existing Zallet config file to be overwritten.
    ///
    /// Only applies when the output is named explicitly with -o/--output; the
    /// default config path is never overwritten.
    #[arg(short, long)]
    pub(crate) force: bool,

    /// Temporary flag ensuring any beta users are aware the config is not stable.
    #[arg(long)]
    pub(crate) this_is_beta_code_and_you_will_need_to_recreate_the_example_later: bool,
}

/// `migrate-zcash-conf` subcommand
#[cfg(all(zallet_build = "wallet", feature = "zcashd-import"))]
#[derive(Debug, Parser)]
#[cfg_attr(outside_buildscript, derive(Command))]
pub(crate) struct MigrateZcashConfCmd {
    /// Specify `zcashd` configuration file.
    ///
    /// Relative paths will be prefixed by `zcashd_datadir` location.
    #[arg(long, default_value = "zcash.conf")]
    pub(crate) conf: PathBuf,

    /// Specify `zcashd` data directory (this path cannot use '~').
    #[arg(long)]
    pub(crate) zcashd_datadir: Option<PathBuf>,

    /// Allow a migration when warnings are present.
    #[arg(long)]
    pub(crate) allow_warnings: bool,

    /// Where to write the Zallet config file.
    ///
    /// - By default, the default Zallet config file path is used.
    /// - The value `-` will write the config to stdout.
    #[arg(short, long)]
    pub(crate) output: Option<String>,

    /// Force an existing Zallet config file to be overwritten.
    ///
    /// Only applies when the output is named explicitly with -o/--output; the
    /// default config path is never overwritten.
    #[arg(short, long)]
    pub(crate) force: bool,

    /// Temporary flag ensuring any beta users are aware the migration is not stable.
    #[arg(long)]
    pub(crate) this_is_beta_code_and_you_will_need_to_redo_the_migration_later: bool,
}

/// `migrate-zcashd-wallet` subcommand
#[cfg(all(zallet_build = "wallet", feature = "zcashd-import"))]
#[derive(Debug, Parser)]
#[cfg_attr(outside_buildscript, derive(Command))]
pub(crate) struct MigrateZcashdWalletCmd {
    /// Specify location of the `zcashd` `wallet.dat` file.
    ///
    /// Relative paths will be prefixed by `zcashd_datadir` location.
    #[arg(long, default_value = "wallet.dat")]
    pub(crate) path: PathBuf,

    /// Specify `zcashd` data directory (this path cannot use '~').
    #[arg(long)]
    pub(crate) zcashd_datadir: Option<PathBuf>,

    /// Allow import of wallet data from multiple `zcashd` `wallet.dat` files. Each imported wallet
    /// will create a distinct set of accounts in `zallet`. Attempts to import wallet data
    /// corresponding to an already-imported wallet will result in an error.
    #[arg(long)]
    pub(crate) allow_multiple_wallet_imports: bool,

    /// Specify the path to a local `zcashd` installation directory.
    ///
    /// When set, the `db_dump` utility from that installation's `zcutil/bin` directory is
    /// used to extract data from the `wallet.dat` file. By default the Berkeley DB 6.2
    /// `db_dump` vendored with Zallet is used, falling back to one on the system `PATH`,
    /// so a local `zcashd` installation is not required.
    #[arg(long)]
    pub(crate) zcashd_install_dir: Option<PathBuf>,

    /// Allow a migration when warnings are present. If set to `false`, any warning will be treated
    /// as an error and cause the migration to abort. Setting this to `true` will allow the import
    /// of partially-corrupted wallets, or wallets that contain transaction data from consensus
    /// forks of the Zcash chain (only transaction data corresponding to known consensus rules will
    /// be imported.)
    #[arg(long)]
    pub(crate) allow_warnings: bool,

    /// Allow the migration to complete even when some accounts or transparent spending
    /// keys in the `zcashd` wallet could not be imported. The skipped items are reported
    /// as warnings; they remain accessible only via the original `wallet.dat` file. A
    /// migration that imports nothing at all is an error regardless of this flag.
    #[arg(long)]
    pub(crate) allow_partial_import: bool,

    /// Skip chain scanning during migration. Keys, accounts, and transaction data are
    /// still imported, but block heights and tree state are not resolved from the chain.
    /// Useful when the corresponding chain data is not available.
    #[arg(long)]
    pub(crate) no_scan: bool,

    /// Temporary flag ensuring any beta users are aware the migration is not stable.
    #[arg(long)]
    pub(crate) this_is_beta_code_and_you_will_need_to_redo_the_migration_later: bool,
}

/// `generate-encryption-identity` subcommand
#[cfg(zallet_build = "wallet")]
#[derive(Debug, Parser)]
#[cfg_attr(outside_buildscript, derive(Command))]
pub(crate) struct GenerateEncryptionIdentityCmd {
    /// Where to write the age encryption identity file.
    ///
    /// - By default, the configured `keystore.encryption_identity` path is used.
    /// - The value `-` will write the identity to stdout.
    #[arg(short, long)]
    pub(crate) output: Option<String>,

    /// Encrypt the identity with a passphrase (ASCII-armored).
    ///
    /// You will be prompted for the passphrase (with confirmation),
    /// unless `--passphrase-file` is given.
    #[arg(short, long)]
    pub(crate) passphrase: bool,

    /// Read the passphrase from the first line of the given file instead
    /// of prompting.
    ///
    /// For non-interactive use. Prefer a pipe or file descriptor (`-` for
    /// standard input, or e.g. `/dev/fd/3`) over a regular file; never pass
    /// secrets via command-line arguments or environment variables, which
    /// are visible to other processes.
    #[arg(long, requires = "passphrase", value_name = "PATH")]
    pub(crate) passphrase_file: Option<String>,
}

/// `init-wallet-encryption` subcommand
#[cfg(zallet_build = "wallet")]
#[derive(Debug, Parser)]
#[cfg_attr(outside_buildscript, derive(Command))]
pub(crate) struct InitWalletEncryptionCmd {}

/// `generate-mnemonic` subcommand
#[cfg(zallet_build = "wallet")]
#[derive(Debug, Parser)]
#[cfg_attr(outside_buildscript, derive(Command))]
pub(crate) struct GenerateMnemonicCmd {}

/// `import-mnemonic` subcommand
#[cfg(zallet_build = "wallet")]
#[derive(Debug, Parser)]
#[cfg_attr(outside_buildscript, derive(Command))]
pub(crate) struct ImportMnemonicCmd {}

/// `export-mnemonic` subcommand
#[cfg(zallet_build = "wallet")]
#[derive(Debug, Parser)]
#[cfg_attr(outside_buildscript, derive(Command))]
#[command(group = ArgGroup::new("seed").multiple(false))]
pub(crate) struct ExportMnemonicCmd {
    /// Output in a PEM encoded format.
    #[arg(short, long)]
    pub(crate) armor: bool,

    /// The UUID of the account from which to export.
    #[arg(group = "seed")]
    pub(crate) account_uuid: Option<Uuid>,

    /// The ZIP 32 seed fingerprint of the mnemonic phrase to export.
    ///
    /// Use this to export a phrase that has no accounts derived from it yet.
    #[arg(long, group = "seed")]
    pub(crate) seedfp: Option<String>,
}

/// `confirm-backup` subcommand
#[cfg(zallet_build = "wallet")]
#[derive(Debug, Parser)]
#[cfg_attr(outside_buildscript, derive(Command))]
pub(crate) struct ConfirmBackupCmd {
    /// The ZIP 32 seed fingerprint of the mnemonic phrase to confirm.
    ///
    /// May be omitted if the wallet holds exactly one mnemonic phrase.
    #[arg(long)]
    pub(crate) seedfp: Option<String>,
}

/// `import-address` subcommand
#[cfg(all(zallet_build = "wallet", feature = "transparent-key-import"))]
#[derive(Debug, Parser)]
#[cfg_attr(outside_buildscript, derive(Command))]
pub(crate) struct ImportAddressCmd {
    /// The transparent address to watch, or the hex-encoded public key (for a
    /// P2PKH address) or redeem script (for a P2SH address) of the address.
    ///
    /// An address imported by its public key or redeem script tracks the same
    /// transactions as one imported by the bare address, and additionally allows
    /// the wallet to be upgraded to spending capability if the corresponding
    /// private key material is imported later.
    pub(crate) data: String,

    /// The UUID of the account to import the address into.
    ///
    /// By default, the address is imported into the account holding the legacy
    /// `zcashd` pool of funds, as named by the `features.legacy_pool_seed_fingerprint`
    /// option in the Zallet config file.
    #[arg(short, long)]
    pub(crate) account: Option<Uuid>,

    /// Skip the rescan for the imported address's history.
    ///
    /// By default the command connects to the chain backend and queues a rescan
    /// from the account's birthday, so that the next `zallet start` discovers
    /// existing transactions involving the imported address. With this flag the
    /// chain backend is not needed, but only transactions in blocks scanned
    /// after the import will be detected.
    #[arg(long)]
    pub(crate) no_rescan: bool,
}

/// `add-rpc-user` subcommand
#[derive(Debug, Parser)]
#[cfg_attr(outside_buildscript, derive(Command))]
pub(crate) struct AddRpcUserCmd {
    /// The username to add.
    pub(crate) username: String,
}

/// `rpc` subcommand
#[cfg(feature = "rpc-cli")]
#[derive(Debug, Parser)]
#[cfg_attr(outside_buildscript, derive(Command))]
pub(crate) struct RpcCliCmd {
    /// Client timeout in seconds during HTTP requests, or 0 for no timeout.
    ///
    /// Default is 900 seconds.
    ///
    /// The server timeout is configured with the `rpc.timeout` option in the
    /// configuration file.
    #[arg(long)]
    pub(crate) timeout: Option<u64>,

    /// The JSON-RPC command to send to Zallet.
    ///
    /// Use `zallet rpc help` to get a list of RPC endpoints.
    pub(crate) command: String,

    /// Any parameters for the command, as JSON values.
    ///
    /// A parameter of the form `@PATH` is read from the first line of `PATH`
    /// instead, and passed as a JSON string. Use this for secrets such as the
    /// spending key given to `z_importkey`: command-line arguments are visible
    /// to other processes and are recorded in shell history.
    ///
    /// `@-` reads from standard input, prompting without echo if it is a
    /// terminal. `@/dev/fd/3` reads from a caller-supplied file descriptor.
    pub(crate) params: Vec<String>,
}

#[derive(Debug, Parser)]
#[cfg_attr(outside_buildscript, derive(Command, Runnable))]
pub(crate) enum RepairCmd {
    TruncateWallet(TruncateWalletCmd),
    CheckWitnesses(CheckWitnessesCmd),
}

/// Checks whether the wallet can construct a witness for each of its spendable notes.
///
/// Prints the block ranges that need rescanning to repair missing witness data, one
/// `start..end` range per line, and prints nothing if there are none.
///
/// This only examines notes the wallet holds, so it cannot detect a note commitment tree that
/// disagrees with the chain's at positions where the wallet has no note of its own. Finding
/// nothing here does not prove the wallet's trees are sound; if `zallet start` is exiting with
/// a note commitment tree conflict, rewind the wallet with `zallet repair truncate-wallet`.
#[derive(Debug, Parser)]
#[cfg_attr(outside_buildscript, derive(Command))]
pub(crate) struct CheckWitnessesCmd {
    /// Queue the reported ranges to be rescanned the next time the wallet syncs.
    ///
    /// Without this flag the command only reports, and does not modify the wallet.
    #[arg(long)]
    pub(crate) queue_rescan: bool,
}

/// Truncates the wallet database to at most the specified height.
///
/// Upon successful truncation, this method returns the height to which the data store was
/// actually truncated. `zallet start` will then sync the wallet as if this height was the
/// last observed chain tip height.
///
/// There may be restrictions on heights to which it is possible to truncate.
/// Specifically, it will only be possible to truncate to heights at which is is possible
/// to create a witness given the current state of the wallet's note commitment tree.
#[derive(Debug, Parser)]
#[cfg_attr(outside_buildscript, derive(Command))]
pub(crate) struct TruncateWalletCmd {
    /// The maximum height the wallet may treat as a mined block.
    ///
    /// Zallet may choose a lower block height to which the data store will be truncated
    /// if it is not possible to truncate exactly to the specified height.
    pub(crate) max_height: u32,
}

#[derive(Debug, Parser)]
#[cfg_attr(outside_buildscript, derive(Command, Runnable))]
pub(crate) enum RegtestCmd {
    /// Generate a default account and return a transparent address for miner outputs.
    #[cfg(zallet_build = "wallet")]
    GenerateAccountAndMinerAddress(GenerateAccountAndMinerAddressCmd),
}

#[cfg(zallet_build = "wallet")]
#[derive(Debug, Parser)]
#[cfg_attr(outside_buildscript, derive(Command))]
pub(crate) struct GenerateAccountAndMinerAddressCmd {}
