//! Generated client stubs for the vendored Zinder `WalletQuery` wire contract.
//!
//! The module tree mirrors the proto package hierarchy (`zinder.v1.wallet`,
//! `zinder.v1.ops`) so prost's cross-package references resolve. Regenerated by
//! [`build.rs`](../../../../build.rs) from `zallet/proto/zinder/`.

#[allow(
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    missing_docs,
    unused_qualifications,
    unreachable_pub,
    unused_lifetimes,
    rust_2018_idioms,
    reason = "generated protobuf code mirrors the vendored Zinder wire contract"
)]
pub(crate) mod zinder {
    pub(crate) mod v1 {
        pub(crate) mod ops {
            include!(concat!(env!("OUT_DIR"), "/zinder.v1.ops.rs"));
        }
        pub(crate) mod wallet {
            include!(concat!(env!("OUT_DIR"), "/zinder.v1.wallet.rs"));
        }
    }
}

pub(crate) use zinder::v1::wallet;
