//! Pins the generated JSON-RPC method reference that is included in the Zallet book.
//!
//! The reference is generated by `generate_rpc_book_reference` in `build.rs` from the
//! rustdoc on the RPC traits, and a copy is checked in at `book/src/rpc/methods.md` so
//! the book can `{{#include}}` it. This test fails whenever the two diverge.

#![cfg(zallet_build = "wallet")]

/// The reference generated by `build.rs` for this compilation.
const GENERATED: &str = include_str!(concat!(env!("OUT_DIR"), "/rpc_methods.md"));

/// The copy checked into the book.
const BOOK_COPY_PATH: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../book/src/rpc/methods.md");

#[test]
fn book_rpc_reference_is_current() {
    if std::env::var_os("ZALLET_BLESS").is_some() {
        std::fs::write(BOOK_COPY_PATH, GENERATED).expect("book copy is writable");
    }

    let book_copy = std::fs::read_to_string(BOOK_COPY_PATH).expect("book copy exists");

    // Compare with normalized line endings: on Windows runners, Git's autocrlf
    // checks the book copy out with CRLF line endings.
    assert!(
        book_copy.replace("\r\n", "\n") == GENERATED.replace("\r\n", "\n"),
        "book/src/rpc/methods.md does not match the rustdoc on the RPC traits; \
         regenerate it with `ZALLET_BLESS=1 cargo test -p zallet-core --test book_rpc_reference`",
    );
}
